backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "markdown"}
      - file: "src/pages/event/index.md"
        label: "Event"
        name: "event"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event-page"}
          - {label: Title, name: title, widget: string}
          - {label: Events, name: events, widget: list, fields:[{label: Name, name: name, widget: text}, {label: Date, name: date, widget: text}]}
      - file: "src/pages/team/index.md"
        label: "Team"
        name: "team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Team, name: team, widget: list, fields: [ {label: Name, name: name, widget: text}, {label: Image, name: image, widget: image}, {label: Text, name: text, widget: markdown}]}
